### ISSUE TITLE
online docs: list all modules

### ISSUE THREAD

**Issue by c-cube** [gildor478/ounit#12]
currently https://gildor478.github.io/ounit/ounit2/index.html seems to be an introduction/entrypoint, which is good, but it lacks a list of all the available modules. So one has no way of discovering all the existing modules except for tab-completion with merlin (e.g. `OUnitLoggerHTML`? What does that do? Are there actually other runners provided with OUnit?)

**Comment by gildor478** [comment]
advanced modules are supposed to be hidden to normal users (they are more or less internal). 

Normal users should only use OUnit2 (or OUnit if they are still on v1). I did that to restrict the usage of more advanced and unstable features. What is exposed in OUnit2 (the module) is what I commit to be stable.

**Comment by c-cube** [comment]
But then I don't know, looking at the docs, how to do the following:

- get colored output (the biggest feature advertised by alcotest :sweat_smile:)
- get junit reports, which I needed a while ago when I was using jenkins
- write my own custom reporter

and I'm not even aware OUnit *can* do that.

**Comment by gildor478** [comment]
Good point, but they are activated using environment variable or command line flags. You don't need to know the code.

* OUNIT_CI=true to get colors and CI integration
* OUNIT_OUTPUT_HTML_DIR=... to get HTML rendering
* OUNIT_OUTPUT_JUNIT_FILE=... to get a JUnit file

Writing your own custom reporter is an advanced topic and you should look at the code and copy paste one of the existing one -- it is unfortunately not really simple. 

Maybe we should just this options to the main page of OUnit2 (except for the own custom reporter).

**Comment by c-cube** [comment]
yes, if the main docs would mention all the supported flags (or even propose them as CLI arguments) that'd be very helpful. I'd always use the colorful output, I think :-)
