### ISSUE TITLE
AssertCodePosition test fails on bytecode

### ISSUE THREAD

**Issue by glondu** [gildor478/ounit#21]
This test fails on bytecode architectures. See for example https://buildd.debian.org/status/fetch.php?pkg=ounit&arch=armel&ver=2.2.3-1&stamp=1597660518&raw=0

**Comment by gildor478** [comment]
Do you know if this something new or it was already there before (e.g. 2.2.2)

**Comment by glondu** [comment]
The previous version in Debian was 2.0.8, and tests were turned off.

**Comment by gildor478** [comment]
OK, I think it has always been here in this case. I need to find a way to reproduce that locally (force dune to use bytcode only version of the test).

**Comment by glondu** [comment]
> I need to find a way to reproduce that locally (force dune to use bytcode only version of the test).

Removing /usr/bin/ocamlopt* (e.g. in a chroot) seems sufficient.
