### ISSUE TITLE
Workaround for renaming doesn't work on windows

### ISSUE THREAD

**Issue by fdopen** [gildor478/ounit#8]
The workaround for renaming oUnit doesn't work on windows and probably with other filesystems that are case insensitive. 
- https://github.com/gildor478/ounit/blob/d0e06a99cc2afa0ba29abd99c2b1f7e228f75ab0/Makefile#L54 will install a directory called oUnit
- https://github.com/gildor478/ounit/blob/d0e06a99cc2afa0ba29abd99c2b1f7e228f75ab0/Makefile#L55 will re-use this directory and overwrite its content, because the directories oUnit and ounit are identic.
- when the package is installed and `oUnit` is referenced instead of ounit inside a dune file, `oUnit` can't be found (the name of the library seems to be determined by the dune-package file, not the directory name). ocamlfind doesn't seem to have this problem.

**Comment by gildor478** [comment]
I need to try this scenario with Windows, to check what can be done. 

If I install ounit 2.1.2 and I have the following dune file:

dune:
(test
   (name foobar)
   (libraries oUnit))

You think the test will fail to build?

**Comment by fdopen** [comment]
Yes, I've create #9 in order to see, if I can trigger the error with the CI.

**Comment by fdopen** [comment]
Windows failure: https://ci.appveyor.com/project/gildor478/ounit/builds/27635212#L653
OS X is also affected:  https://travis-ci.org/gildor478/ounit/jobs/589049420#L1530

**Comment by gildor478** [comment]
Thanks a lot. I can now reproduce the problem. Maybe I can just use REVDEPS=re. 

I see 2 solutions for now:
1. Use the --metadir to install a file META.oUnit in a different directory with the name oUnit -- but I am unsure if it will work correctly
2. Create a package ounit2 + ounit2-lwt and install the libraries in ounit2, continue to use the "ocamlfind install oUnit" and depends on ounit2. I think this one will solve the problem...

**Comment by gildor478** [comment]
The commit 53b9d1a4 should have solved the issue.

I'll do a release soon, let me know if you think there is a problem.
