### ISSUE TITLE
Disable OUnitCheckEnv

### ISSUE THREAD

**Issue by tmcgilchrist** [gildor478/ounit#86]
More a question than an issue, Is there a way to disable the `OUnitCheckEnv` checking when running a test via `run_test_tt`? It doesn't appear to be configurable or I'm missing where it is.

```
   open OUnit

    let _ =
      let suite = "Tests" >::: test_cases in
      if not (was_successful (run_test_tt suite)) then exit 1
```

**Comment by gildor478** [comment]
No, there is no way to disable it.

Do you actually have a use case for disabling it?
